name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS 2 Humble
      uses: ros-tooling/setup-ros@v0.4
      with:
        # правильний параметр замість `distro`
        required-ros-distributions: humble
        # одразу оновлюємо rosdep
        rosdep_update: true

    - name: Install Python tooling
      run: |
        python3 -m pip install -U \
          colcon-common-extensions \
          pytest \
          ament-lint \
          ament_lint_auto

    - name: Build battle_interfaces only & check interfaces
      run: |
        # завжди спершу source ROS
        source /opt/ros/humble/setup.bash
        colcon build --packages-select battle_interfaces --symlink-install --event-handlers console_cohesion+
        source install/setup.bash
        # перевірка, що наші нові msgs/srv генеряться
        ros2 interface show battle_interfaces/msg/TargetArray
        ros2 interface show battle_interfaces/srv/Pointing

    - name: Full build and run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install --event-handlers console_cohesion+
        colcon test
        colcon test-result --verbose

    - name: Run pytest
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        pytest --maxfail=1 --disable-warnings -q
