name: ROS 2 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@master
      with:
        required-ros-distributions: humble

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          python3-empy \
          python3-flake8 \
          python3-pytest \
          python3-pycodestyle \
          ros-humble-ament-lint \
          ros-humble-ament-lint-auto \
          ros-humble-ament-flake8 \
          ros-humble-ament-pep257

    - name: Install Python tooling
      run: |
        pip3 install -U \
          colcon-common-extensions \
          flake8-blind-except \
          flake8-builtins \
          flake8-class-newline \
          flake8-comprehensions \
          flake8-deprecated \
          flake8-import-order \
          flake8-quotes

    - name: Clean workspace
      run: |
        rm -rf build/ install/ log/

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: |
        source install/setup.bash
        colcon test
        colcon test-result --verbose
