name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.4
        with:
          distro: humble

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-colcon-common-extensions \
            ros-humble-ament-lint \
            ros-humble-ament-lint-auto
          python3 -m pip install -U pytest

      - name: Build & Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --event-handlers console_cohesion+
          source install/setup.bash
          colcon test --packages-select ament_lint_auto
          colcon test-result --verbose
          pytest --maxfail=1 --disable-warnings -q
