name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      ROS_DOMAIN_ID: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: humble

      - name: Install system and ROS dependencies
        run: |
          sudo apt update
          # базові інструменти для colcon та rosdep
          sudo apt install -y python3-colcon-common-extensions python3-rosdep
          # оновлюємо базу rosdep (може уперше провалитись, тому || true)
          sudo rosdep init || true
          rosdep update
          # встановлюємо всі залежності вашого workspace
          rosdep install --from-paths src --ignore-src -r -y
          # лишаємо pytest із pip
          python3 -m pip install -U pytest

      - name: Source ROS 2
        run: echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV

      - name: Build workspace
        run: |
          source $GITHUB_ENV
          colcon build --symlink-install --event-handlers console_cohesion+

      - name: Run linters
        run: |
          source install/setup.bash
          colcon test --packages-select ament_lint_auto
          colcon test-result --verbose

      - name: Run pytest
        run: |
          source install/setup.bash
          pytest --maxfail=1 --disable-warnings -q
