name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      ROS_DOMAIN_ID: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.4
        with:
          distro: humble

      - name: Install Python tooling
        run: |
          sudo apt update
          sudo apt install -y python3-pip empy    # empy потрібен для роботи colcon
          python3 -m pip install -U \
            colcon-common-extensions \
            ament-lint \
            pytest

      - name: Build workspace
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE         # переконаємося, що в корені репо
          source /opt/ros/humble/setup.bash
          rm -rf build install log
          colcon build --symlink-install --event-handlers console_cohesion+

      - name: Run linters
        shell: bash
        run: |
          source install/setup.bash
          colcon test --packages-select ament_lint_auto
          colcon test-result --verbose

      - name: Run pytest
        shell: bash
        run: |
          source install/setup.bash
          pytest --maxfail=1 --disable-warnings -q
