name: ROS 2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2 Humble
      uses: ros-tooling/setup-ros@master
      with:
        required-ros-distributions: humble

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          python3-empy \
          python3-flake8 \
          python3-pytest \
          python3-pycodestyle \
          ros-humble-ament-lint \
          ros-humble-ament-lint-auto \
          ros-humble-ament-flake8 \
          ros-humble-ament-pep257

    - name: Install Python tooling
      run: |
        python3 -m pip install --upgrade pip
        pip install colcon-common-extensions

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --event-handlers console_direct+

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --event-handlers console_direct+
        colcon test-result --verbose
