name: Flake8 Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # <-- додали можливість запуску вручну


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install flake8 with plugins
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-import-order flake8-quotes flake8-bugbear

    - name: Run flake8 using .flake8 config
      run: |
        flake8 src/ --config=.flake8
