name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      ROS_DOMAIN_ID: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.4
        with:
          distro: humble

      - name: Cleanup conflicting em/empy
        run: |
          sudo python3 -m pip uninstall -y em || true
          sudo python3 -m pip uninstall -y empy || true
          sudo rm -f /usr/local/bin/em /usr/local/bin/em.py || true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-empy \
            python3-colcon-common-extensions \
            ros-humble-ament-lint \
            ros-humble-ament-lint-auto

      - name: Install Python tooling
        run: |
          python3 -m pip install --upgrade pytest

      - name: Build workspace
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --event-handlers console_cohesion+

      - name: Run linters
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          colcon test --packages-select ament_lint_auto
          colcon test-result --verbose

      - name: Run pytest
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          pytest --maxfail=1 --disable-warnings -q
