name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.4
        with:
          distro: humble

      - name: Install system tooling
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-empy \
            python3-lark-parser \
            python3-flake8 \
            python3-pep257 \
            python3-pydocstyle \
            ros-humble-ament-lint \
            ros-humble-ament-lint-auto

      - name: Install Python-засоби
        run: |
          python3 -m pip install -U \
            colcon-common-extensions \
            pytest

      - name: Uninstall rogue `em` package
        run: |
          python3 -m pip uninstall -y em || true

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --event-handlers console_cohesion+

      - name: Run linters
        run: |
          source /opt/ros/humble/setup.bash
          # flake8 та pep257 тепер підхопляться з apt-пакетів
          colcon test --packages-select ament_lint_auto ament_flake8 ament_pep257
          colcon test-result --verbose

      - name: Run pytest
        run: |
          source /opt/ros/humble/setup.bash
          pytest --maxfail=1 --disable-warnings -q
